<div class="row">
<center>
P R O V I N C I A D E E N T R E R Í O S<br>
<u>MINISTERIO DE PLANEAMIENTO, INFRAESTRUCTURA Y SERVICIOS<br>
DIRECCIÓN PROVINCIAL DE VIALIDAD<br>
CERTIFICADO DE OBRA POR CONTRATO</u>
</center>
</div>